# Use a base image with Java 22 installed
FROM openjdk:22

# Copy the compiled JAR file into the container at /app
ADD target/store-0.0.1.jar store.jar

# Expose port 8080
EXPOSE 8080

# Command to run the application when the container starts
ENTRYPOINT ["java", "-jar", "store.jar"]