version: '3.8'

services:
  spring-boot-app:
    image: jvanderlith085/store:latest # Replace with your image name
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres-server:5432/leadgen
      - DB_USERNAME=admin
      - DB_PASSWORD=admin

  postgres-server:
    image: postgres:latest
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p@admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'

volumes:
  postgres-data: