spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  mvc:
    log-request-details: true  # Enables detailed logging of incoming requests
    jackson:
      serialization:
        fail-on-empty-beans: false
    main:
      allow-bean-definition-overriding: true
  server:
    error:
      include-message: always
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
    org.springframework.boot.actuate: DEBUG

